quarkus:
  application:
    name: nautilux
    version: 1.0.0
  
  # Database Configuration
  datasource:
    db-kind: postgresql
    username: nautilux
    password: nautilux
    jdbc:
      url: jdbc:postgresql://localhost:5432/nautilux
    health:
      enabled: true
  
  # Hibernate ORM - Optimized for performance
  hibernate-orm:
    database:
      generation: validate
    log:
      sql: false
    statistics: false
    # Reduce memory usage
    batch-size: 20
    order-inserts: true
    order-updates: true
  
  # Flyway Migration
  flyway:
    migrate-at-start: true
    baseline-on-migrate: true
  
  # HTTP Configuration - Optimized
  http:
    port: 8080
    host: 0.0.0.0
    cors:
      ~: true
      origins: "*"
      methods: GET,POST,PUT,DELETE,OPTIONS
      headers: accept,authorization,content-type,x-requested-with
      exposed-headers: Content-Disposition
      access-control-max-age: 24H
    # Reduce thread pool size
    thread-pool:
      max-threads: 10
      min-threads: 2
  
  # OpenAPI/Swagger
  smallrye-openapi:
    path: /q/swagger-ui
    info:
      title: Nautilux API
      version: 1.0.0
      description: Smart Coral Reef Health Monitoring System API
  
  # Health Checks
  smallrye-health:
    root-path: /q/health
  
  # Logging - Reduced verbosity
  log:
    level: WARN
    category:
      "com.nautilux": INFO
      "org.apache.camel": WARN
      "org.hibernate.SQL": WARN
      "org.hibernate.type.descriptor.sql.BasicBinder": WARN

# Camel Configuration - Simplified
camel:
  # Main Camel Context
  main:
    name: nautilux-camel-context
    auto-startup: true
  
  # Component Configurations - Minimal
  component:
    # File Component
    file:
      default-buffer-size: 64000
      default-read-lock: marker-file
      default-read-lock-timeout: 15000
    
    # HTTP Component
    http:
      default-connection-timeout: 15000
      default-socket-timeout: 15000
    
    # Timer Component
    timer:
      default-period: 5000

# External API Configuration - Simplified
external:
  noaa:
    base-url: https://coralreefwatch.noaa.gov/api/v1
    api-key: ${NOAA_API_KEY:demo-key}
  
  coralnet:
    base-url: https://coralnet.ucsd.edu/api
    api-key: ${CORALNET_API_KEY:demo-key}

# Ray Service Configuration
ray:
  service:
    url: ${RAY_SERVICE_URL:http://localhost:8000}
    timeout: 15000

# Data Processing Configuration - Optimized
processing:
  image:
    max-size: 5MB
    supported-formats: jpg,jpeg,png
    quality-threshold: 0.7
  
  sonar:
    max-file-size: 25MB
    supported-formats: csv,json
    sampling-rate: 22050
  
  batch:
    max-concurrent-jobs: 2
    timeout: 120000

# Storage Configuration - Simplified
storage:
  local:
    base-path: ${LOCAL_STORAGE_PATH:./data/storage}

# Monitoring Configuration - Basic
monitoring:
  prometheus:
    enabled: false
  logging:
    level: WARN
    format: simple 